services:
  app:
    build: .
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-west-2
      - DYNAMODB_TABLE=your-table-name
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    tty: true

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"

