services:
  app:
    build: .
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    tty: true

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"

